name: rd_online_shop_new

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2


dependencies:
  flutter:
    sdk: flutter

  geolocator: ^14.0.0
  geocoding: ^4.0.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"


flutter:
  uses-material-design: true

  assets:
    - assets/icon/logo.png