name: rd_online_shop_new
description: RD Online Shop
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  geolocator: ^13.0.2
  geocoding: ^5.0.0
  speech_to_text: ^7.0.0
  image_picker: ^1.1.2
  firebase_core: 4.14.0
  cloud_firestore: 6.9.0
  http: ^1.6.0
  crypto: ^3.0.6
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  firebase_auth: 6.6.0
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.4.0
  pdf: ^3.11.3
  excel: ^4.0.6
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  firebase_messaging: 16.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/rd_logo.png
    - assets/images/rd_offer_banner.png
    - assets/products/
    - assets/categories/