
android.useAndroidX=true

# This builtInKotlin flag was added automatically by Flutter migrator

# This newDsl flag was added automatically by Flutter migrator

kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false
org.gradle.caching=false
org.gradle.warning.mode=none
org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -XX:+UseSerialGC -XX:TieredStopAtLevel=1 -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.daemon=false
kotlin.compiler.execution.strategy=in-process

android.newDsl=false
android.builtInKotlin=false

org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr

org.gradle.internal.instrumentation.agent=false
