
android.useAndroidX=true

# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false

# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false

kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false
org.gradle.caching=false
org.gradle.warning.mode=none
org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=384m -XX:+UseSerialGC -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.daemon=false
org.gradle.vfs.watch=false
kotlin.compiler.execution.strategy=in-process
org.gradle.internal.instrumentation.agent=false
