// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgOWeLakmDctpfsUqEWQT4mJyRmeygrOA',
    appId: '1:993981240325:web:f1b33b5e273ffbc242b86c',
    messagingSenderId: '993981240325',
    projectId: 'rd-online-shop-d7c72',
    authDomain: 'rd-online-shop-d7c72.firebaseapp.com',
    storageBucket: 'rd-online-shop-d7c72.firebasestorage.app',
    measurementId: 'G-M8T90J2S2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB5jsBZ6FbN6eQaCyp7zJ_Y8fIgGqgGr8',
    appId: '1:993981240325:android:a48be8aab42152df42b86c',
    messagingSenderId: '993981240325',
    projectId: 'rd-online-shop-d7c72',
    storageBucket: 'rd-online-shop-d7c72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqSnm5SVJsSyuwm3zb_7PcreDKYH-viAE',
    appId: '1:993981240325:ios:1f06d9539c18db5f42b86c',
    messagingSenderId: '993981240325',
    projectId: 'rd-online-shop-d7c72',
    storageBucket: 'rd-online-shop-d7c72.firebasestorage.app',
    iosBundleId: 'com.example.rdOnlineShopNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqSnm5SVJsSyuwm3zb_7PcreDKYH-viAE',
    appId: '1:993981240325:ios:1f06d9539c18db5f42b86c',
    messagingSenderId: '993981240325',
    projectId: 'rd-online-shop-d7c72',
    storageBucket: 'rd-online-shop-d7c72.firebasestorage.app',
    iosBundleId: 'com.example.rdOnlineShopNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgOWeLakmDctpfsUqEWQT4mJyRmeygrOA',
    appId: '1:993981240325:web:7a62129eb3e0c4cc42b86c',
    messagingSenderId: '993981240325',
    projectId: 'rd-online-shop-d7c72',
    authDomain: 'rd-online-shop-d7c72.firebaseapp.com',
    storageBucket: 'rd-online-shop-d7c72.firebasestorage.app',
    measurementId: 'G-R68C3BXN5L',
  );
}
